/* Demo syllabi: notes, worked examples and question banks.
 * These are ordinary syllabus records, the same shape a school imports from
 * JSON (see syllabi/TEMPLATE.json). In the question helpers below the correct
 * option is always written FIRST; the demo seed shuffles the options. Imported
 * syllabi keep their option order and use the `answer` index as given. */
(function (A) {
  "use strict";

  function mcq(prompt, options, explanation, marks) { return { type: "mcq", prompt: prompt, options: options, answer: 0, explanation: explanation || "", marks: marks || 1 }; }
  function tf(prompt, answer, explanation) { return { type: "tf", prompt: prompt, answer: answer, explanation: explanation || "", marks: 1 }; }
  function short(prompt, accepted, explanation, marks) { return { type: "short", prompt: prompt, answer: accepted, explanation: explanation || "", marks: marks || 1 }; }
  function num(prompt, value, explanation, marks, tolerance) { var q = { type: "numeric", prompt: prompt, answer: value, explanation: explanation || "", marks: marks || 1 }; if (tolerance != null) q.tolerance = tolerance; return q; }
  function st(prompt, markScheme, marks) { return { type: "structured", prompt: prompt, markScheme: markScheme, marks: marks }; }
  function ex(q, a) { return { q: q, a: a }; }

  var ZIMSEC_MATHS = {
    id: "syl_zimsec_maths_4004", board: "ZIMSEC", level: "O-Level", subject: "Mathematics", code: "4004",
    description: "Core O-Level Mathematics topics with notes, worked examples and exam-style questions.",
    gradeScale: [{ grade: "A", min: 75 }, { grade: "B", min: 65 }, { grade: "C", min: 50 }, { grade: "D", min: 40 }, { grade: "E", min: 30 }, { grade: "U", min: 0 }],
    topics: [
      {
        id: "zm_sets", title: "Sets", estMinutes: 40, term: 1, summary: "Set notation, Venn diagrams and counting with two sets.",
        notes: [
          "## What is a set?",
          "A **set** is a well-defined collection of objects called **elements** or **members**. Sets are named with capital letters and listed inside curly brackets.",
          "- A = {2, 4, 6, 8} is the set of even numbers from 2 to 8.",
          "- 4 ∈ A means \"4 is an element of A\"; 5 ∉ A means \"5 is not an element of A\".",
          "- n(A) is the **number of elements** in A, so n(A) = 4.",
          "## Key vocabulary",
          "| Term | Symbol | Meaning |",
          "|---|---|---|",
          "| Universal set | ξ | everything under consideration |",
          "| Empty set | ∅ or { } | a set with no elements |",
          "| Subset | A ⊂ B | every element of A is also in B |",
          "| Union | A ∪ B | elements in A **or** B (or both) |",
          "| Intersection | A ∩ B | elements in **both** A and B |",
          "| Complement | A′ | elements of ξ that are **not** in A |",
          "## Venn diagrams",
          "A rectangle represents the universal set and circles represent the sets inside it. The overlap of two circles is their intersection.",
          "## Counting with two sets",
          "[[n(A ∪ B) = n(A) + n(B) − n(A ∩ B)]]",
          "> Tip: in Venn diagram problems, fill in the **intersection first**, then work outwards.",
          "## Number of subsets",
          "A set with n elements has 2^n subsets, including ∅ and the set itself.",
        ].join("\n"),
        examples: [
          ex("ξ = {1, 2, 3, …, 10}, A = {even numbers}, B = {multiples of 3}. List A ∩ B and A ∪ B.",
            "A = {2, 4, 6, 8, 10} and B = {3, 6, 9}.\nA ∩ B = {6}, the only number in both sets.\nA ∪ B = {2, 3, 4, 6, 8, 9, 10}."),
          ex("In a class of 40 students, 25 take Geography, 18 take History and 7 take both. How many take neither?",
            "n(G ∪ H) = n(G) + n(H) − n(G ∩ H) = 25 + 18 − 7 = 36\nNeither = 40 − 36 = 4 students."),
        ],
        questions: [
          mcq("If A = {a, b, c, d} and B = {c, d, e}, what is A ∩ B?", ["{c, d}", "{a, b, c, d, e}", "{a, b}", "{e}"], "The intersection contains only the elements found in both sets: c and d."),
          num("A = {p, q, r, s, t}. Find n(A).", 5, "Count the elements: p, q, r, s, t gives 5."),
          num("How many subsets does the set {1, 2, 3} have?", 8, "A set with 3 elements has 2^3 = 8 subsets, including ∅ and the set itself."),
          num("n(A) = 15, n(B) = 12 and n(A ∩ B) = 5. Find n(A ∪ B).", 22, "n(A ∪ B) = 15 + 12 − 5 = 22."),
          tf("The empty set is a subset of every set.", true, "∅ has no elements, so every one of its (zero) elements is in any other set."),
          mcq("ξ = {1, 2, 3, 4, 5, 6} and A = {1, 3, 5}. What is A′?", ["{2, 4, 6}", "{1, 3, 5}", "{ }", "{1, 2, 3, 4, 5, 6}"], "A′ is everything in ξ that is not in A."),
          st("In a group of 50 learners, 30 like football, 25 like netball and x like both. Every learner likes at least one of the two sports.\n(a) Write an equation in x.\n(b) Solve it to find how many like both.",
            "(a) 30 + 25 − x = 50  [1]\n(b) 55 − x = 50, so x = 5  [1]\nAccept any correct method shown on a Venn diagram.", 2),
        ],
      },
      {
        id: "zm_indices", title: "Indices and Standard Form", estMinutes: 45, term: 1, summary: "Laws of indices, zero, negative and fractional indices, standard form.",
        notes: [
          "## Laws of indices",
          "For any non-zero base a:",
          "| Law | Rule | Example |",
          "|---|---|---|",
          "| Multiply: add the powers | a^m × a^n = a^{m+n} | 2^3 × 2^4 = 2^7 |",
          "| Divide: subtract the powers | a^m ÷ a^n = a^{m−n} | 5^6 ÷ 5^2 = 5^4 |",
          "| Power of a power | (a^m)^n = a^{mn} | (3^2)^3 = 3^6 |",
          "| Zero index | a^0 = 1 | 7^0 = 1 |",
          "| Negative index | a^{−n} = 1 ÷ a^n | 2^{−3} = 1/8 |",
          "| Fractional index | a^{m/n} = (ⁿ√a)^m | 8^{2/3} = 4 |",
          "> Tip: with fractional indices, take the **root first**, then the power. The numbers stay small.",
          "## Standard form",
          "A number is in **standard form** when it is written as",
          "[[A × 10^n, where 1 ≤ A < 10 and n is an integer]]",
          "- Large numbers have a positive n: 45 000 = 4.5 × 10^4",
          "- Small numbers have a negative n: 0.0032 = 3.2 × 10^{−3}",
          "## Calculating in standard form",
          "- **Multiply**: multiply the A parts and **add** the powers, then adjust.",
          "- **Divide**: divide the A parts and **subtract** the powers.",
          "- **Add or subtract**: first write both numbers with the same power of 10.",
        ].join("\n"),
        examples: [
          ex("Evaluate 16^{3/4}.", "Root first: ⁴√16 = 2\nThen the power: 2^3 = 8\nSo 16^{3/4} = 8"),
          ex("Calculate (3 × 10^5) × (4 × 10^{−2}), giving your answer in standard form.",
            "Multiply the numbers: 3 × 4 = 12\nAdd the powers: 10^{5 + (−2)} = 10^3\n12 × 10^3 is not in standard form because 12 ≥ 10, so write 12 = 1.2 × 10^1\nAnswer: 1.2 × 10^4"),
        ],
        questions: [
          num("Evaluate 2^5.", 32, "2 × 2 × 2 × 2 × 2 = 32"),
          num("Evaluate 5^0 + 4^{1/2}.", 3, "5^0 = 1 and 4^{1/2} = √4 = 2, so the total is 3."),
          mcq("Simplify x^7 ÷ x^3.", ["x^4", "x^10", "x^21", "x^{7/3}"], "When dividing, subtract the powers: 7 − 3 = 4."),
          mcq("Write 0.000 56 in standard form.", ["5.6 × 10^{−4}", "5.6 × 10^{−3}", "56 × 10^{−5}", "5.6 × 10^4"], "Move the decimal point 4 places to the right to get 5.6, so the power is −4."),
          num("Evaluate 8^{2/3}.", 4, "∛8 = 2, then 2^2 = 4."),
          mcq("Evaluate 2^{−3}.", ["1/8", "−8", "−6", "8"], "A negative index means a reciprocal: 2^{−3} = 1 ÷ 2^3 = 1/8."),
          mcq("Calculate (6 × 10^8) ÷ (3 × 10^2) in standard form.", ["2 × 10^6", "2 × 10^4", "18 × 10^6", "2 × 10^{10}"], "6 ÷ 3 = 2 and 10^{8−2} = 10^6."),
          st("Given that 3^{x+1} = 81, find x. Show your working.", "81 = 3^4  [1]\nSo x + 1 = 4  [1]\nx = 3  [1]", 3),
        ],
      },
      {
        id: "zm_linear", title: "Linear Equations and Inequalities", estMinutes: 50, term: 1, summary: "Solving equations, simultaneous equations and inequalities.",
        notes: [
          "## Solving linear equations",
          "An equation stays balanced if you do the **same thing to both sides**.",
          "1. Remove brackets by expanding.",
          "2. Collect the terms in x on one side and the numbers on the other.",
          "3. Divide by the coefficient of x.",
          "## Equations with fractions",
          "Multiply every term by the **LCM of the denominators** first. For x/2 + x/3 = 5, multiply by 6: 3x + 2x = 30, so x = 6.",
          "## Simultaneous equations",
          "Two equations with two unknowns can be solved by:",
          "- **Elimination**: make the coefficients of one letter equal, then add or subtract the equations.",
          "- **Substitution**: make one letter the subject, then substitute it into the other equation.",
          "## Linear inequalities",
          "Solve them like equations, using <, >, ≤ or ≥.",
          "> **Reverse the inequality sign** whenever you multiply or divide both sides by a negative number: −2x > 6 gives x < −3.",
          "On a number line, use an **open circle** for < or > and a **closed circle** for ≤ or ≥.",
        ].join("\n"),
        examples: [
          ex("Solve 3(x − 2) = 2x + 5.", "Expand: 3x − 6 = 2x + 5\nSubtract 2x: x − 6 = 5\nAdd 6: x = 11"),
          ex("Solve the simultaneous equations 2x + y = 11 and x − y = 1.",
            "Add the equations to eliminate y: 3x = 12, so x = 4\nSubstitute into x − y = 1: 4 − y = 1, so y = 3\nCheck: 2(4) + 3 = 11 ✓\nAnswer: x = 4, y = 3"),
        ],
        questions: [
          num("Solve 5x + 3 = 28.", 5, "5x = 25, so x = 5."),
          num("Solve 2(x + 4) = 18.", 5, "2x + 8 = 18, so 2x = 10 and x = 5."),
          num("Solve x/3 + 2 = 6.", 12, "x/3 = 4, so x = 12."),
          mcq("Solve −3x ≤ 12.", ["x ≥ −4", "x ≤ −4", "x ≥ 4", "x ≤ 4"], "Divide by −3 and reverse the sign: x ≥ −4."),
          mcq("Solve x + y = 10 and x − y = 4.", ["x = 7, y = 3", "x = 3, y = 7", "x = 6, y = 4", "x = 5, y = 5"], "Adding gives 2x = 14, so x = 7 and y = 3."),
          num("Find the largest integer x that satisfies 4x − 1 < 15.", 3, "4x < 16, so x < 4. The largest integer below 4 is 3."),
          st("Solve the simultaneous equations\n3x + 2y = 16\n2x − y = 6",
            "Multiply the second equation by 2: 4x − 2y = 12  [1]\nAdd to the first: 7x = 28, so x = 4  [1]\nSubstitute: 2(4) − y = 6, so y = 2  [1]", 3),
        ],
      },
      {
        id: "zm_quadratics", title: "Quadratic Equations", estMinutes: 55, term: 2, summary: "Factorisation, the quadratic formula and the discriminant.",
        notes: [
          "## The general quadratic",
          "[[ax^2 + bx + c = 0, where a ≠ 0]]",
          "A quadratic equation has at most **two** solutions (roots).",
          "## Method 1: Factorisation",
          "Find two numbers that **multiply to ac** and **add to b**.",
          "- x^2 + 5x + 6 = 0 → (x + 2)(x + 3) = 0 → x = −2 or x = −3",
          "- If the product of two brackets is zero, **one of them must be zero**.",
          "## Method 2: The quadratic formula",
          "Use it when the quadratic does not factorise easily:",
          "[[x = (−b ± √(b^2 − 4ac)) ÷ 2a]]",
          "The **discriminant** b^2 − 4ac tells you how many real roots there are:",
          "| b^2 − 4ac | Roots |",
          "|---|---|",
          "| greater than 0 | two different real roots |",
          "| equal to 0 | one repeated root |",
          "| less than 0 | no real roots |",
          "## Difference of two squares",
          "[[a^2 − b^2 = (a − b)(a + b)]]",
          "So x^2 − 49 = 0 gives (x − 7)(x + 7) = 0, and x = ±7.",
        ].join("\n"),
        examples: [
          ex("Solve x^2 − x − 12 = 0.", "Find two numbers that multiply to −12 and add to −1: −4 and 3\n(x − 4)(x + 3) = 0\nx = 4 or x = −3"),
          ex("Solve 2x^2 + 3x − 4 = 0, giving answers to 2 decimal places.",
            "a = 2, b = 3, c = −4\nb^2 − 4ac = 9 + 32 = 41\nx = (−3 ± √41) ÷ 4\nx = (−3 + 6.403) ÷ 4 = 0.85  or  x = (−3 − 6.403) ÷ 4 = −2.35"),
        ],
        questions: [
          mcq("Factorise x^2 + 7x + 10.", ["(x + 5)(x + 2)", "(x + 10)(x + 1)", "(x − 5)(x − 2)", "(x + 7)(x + 3)"], "5 × 2 = 10 and 5 + 2 = 7."),
          mcq("Solve x^2 − 9 = 0.", ["x = 3 or x = −3", "x = 9", "x = 3 only", "x = 81"], "Difference of two squares: (x − 3)(x + 3) = 0."),
          num("Find the positive root of x^2 − 2x − 15 = 0.", 5, "(x − 5)(x + 3) = 0, so x = 5 or x = −3."),
          num("Find the value of the discriminant of x^2 + 4x + 1 = 0.", 12, "b^2 − 4ac = 16 − 4 = 12."),
          tf("The equation x^2 + 2x + 5 = 0 has two real roots.", false, "b^2 − 4ac = 4 − 20 = −16, which is negative, so there are no real roots."),
          st("Solve 3x^2 − 5x − 2 = 0 by factorisation.",
            "ac = −6, so use −6 and 1  [1]\n3x^2 − 6x + x − 2 = 0 → 3x(x − 2) + 1(x − 2) = 0 → (3x + 1)(x − 2) = 0  [1]\nx = −1/3 or x = 2  [1]", 3),
        ],
      },
      {
        id: "zm_mensuration", title: "Mensuration", estMinutes: 45, term: 2, summary: "Perimeter, area, arcs and sectors, volume and surface area.",
        notes: [
          "## Perimeter and area",
          "| Shape | Perimeter | Area |",
          "|---|---|---|",
          "| Rectangle | 2(l + w) | l × w |",
          "| Triangle | sum of the sides | ½ × base × height |",
          "| Parallelogram | sum of the sides | base × height |",
          "| Trapezium | sum of the sides | ½(a + b) × h |",
          "| Circle | 2πr (circumference) | πr^2 |",
          "> Units matter: lengths are in cm or m, areas in cm^2 or m^2, and volumes in cm^3 or m^3.",
          "## Arcs and sectors",
          "For a sector with angle θ at the centre:",
          "[[arc length = (θ ÷ 360) × 2πr]]",
          "[[sector area = (θ ÷ 360) × πr^2]]",
          "## Volume and surface area",
          "- **Prism** (constant cross-section): volume = area of cross-section × length",
          "- **Cylinder**: V = πr^2h, curved surface area = 2πrh",
          "- **Cone**: V = ⅓πr^2h",
          "- **Sphere**: V = (4/3)πr^3, surface area = 4πr^2",
          "## Converting units",
          "1 m = 100 cm, 1 m^2 = 10 000 cm^2, 1 m^3 = 1 000 000 cm^3 and 1 litre = 1000 cm^3.",
        ].join("\n"),
        examples: [
          ex("Find the area of a trapezium whose parallel sides are 8 cm and 12 cm, and whose height is 5 cm.", "Area = ½(a + b) × h\n= ½ × (8 + 12) × 5\n= ½ × 20 × 5 = 50 cm^2"),
          ex("A cylindrical tank has radius 0.7 m and height 2 m. Find its capacity in litres. (Take π = 22/7.)", "V = πr^2h = 22/7 × 0.7 × 0.7 × 2 = 3.08 m^3\n1 m^3 = 1000 litres\nCapacity = 3080 litres"),
        ],
        questions: [
          num("Find the area, in cm^2, of a rectangle 12 cm long and 7 cm wide.", 84, "12 × 7 = 84 cm^2"),
          num("Find the area, in cm^2, of a triangle with base 10 cm and height 6 cm.", 30, "½ × 10 × 6 = 30 cm^2"),
          num("Find the circumference, in cm, of a circle of radius 7 cm. (Take π = 22/7.)", 44, "2 × 22/7 × 7 = 44 cm"),
          num("Find the area, in cm^2, of a circle of radius 14 cm. (Take π = 22/7.)", 616, "22/7 × 14 × 14 = 616 cm^2"),
          num("Find the volume, in cm^3, of a cuboid 5 cm by 4 cm by 3 cm.", 60, "5 × 4 × 3 = 60 cm^3"),
          mcq("How many cm^2 are there in 1 m^2?", ["10 000", "100", "1 000", "1 000 000"], "1 m^2 = 100 cm × 100 cm = 10 000 cm^2."),
          st("A sector of a circle has radius 21 cm and an angle of 60° at the centre. (Take π = 22/7.)\n(a) Find the arc length.\n(b) Find the area of the sector.",
            "(a) Arc = 60/360 × 2 × 22/7 × 21  [1] = 22 cm  [1]\n(b) Area = 60/360 × 22/7 × 21^2  [1] = 231 cm^2  [1]", 4),
        ],
      },
      {
        id: "zm_trig", title: "Trigonometry", estMinutes: 50, term: 2, summary: "Pythagoras, SOH CAH TOA, angles of elevation and depression.",
        notes: [
          "## Pythagoras' theorem",
          "In a right-angled triangle with hypotenuse c (the longest side, opposite the right angle):",
          "[[a^2 + b^2 = c^2]]",
          "## The three trigonometric ratios",
          "Label the sides relative to the angle θ: **Opposite**, **Adjacent** and **Hypotenuse**.",
          "[[sin θ = O ÷ H      cos θ = A ÷ H      tan θ = O ÷ A]]",
          "> Memory aid: **SOH CAH TOA**",
          "## Finding a side or an angle",
          "- To find a **side**, choose the ratio that links the side you know with the side you want, then rearrange.",
          "- To find an **angle**, use the inverse function, e.g. θ = tan^{−1}(O ÷ A).",
          "## Angles of elevation and depression",
          "- The **angle of elevation** is measured **upwards** from the horizontal.",
          "- The **angle of depression** is measured **downwards** from the horizontal.",
          "- The angle of elevation from A to B equals the angle of depression from B to A (alternate angles).",
          "## Special values",
          "| θ | 30° | 45° | 60° |",
          "|---|---|---|---|",
          "| sin θ | 0.5 | ≈ 0.707 | ≈ 0.866 |",
          "| cos θ | ≈ 0.866 | ≈ 0.707 | 0.5 |",
          "| tan θ | ≈ 0.577 | 1 | ≈ 1.732 |",
        ].join("\n"),
        examples: [
          ex("A ladder 5 m long leans against a wall with its foot 3 m from the wall. How high up the wall does it reach?", "The ladder is the hypotenuse.\nh^2 + 3^2 = 5^2\nh^2 = 25 − 9 = 16\nh = 4 m"),
          ex("From a point 50 m from the foot of a tower, the angle of elevation of the top is 32°. Find the height of the tower.",
            "Opposite = height h, adjacent = 50 m, so use tan.\ntan 32° = h ÷ 50\nh = 50 × tan 32° = 50 × 0.6249 = 31.2 m (3 s.f.)"),
        ],
        questions: [
          num("A right-angled triangle has shorter sides of 6 cm and 8 cm. Find the hypotenuse in cm.", 10, "√(36 + 64) = √100 = 10 cm"),
          mcq("In a right-angled triangle, which ratio is Opposite ÷ Hypotenuse?", ["sin θ", "cos θ", "tan θ", "none of these"], "SOH: sin = Opposite ÷ Hypotenuse."),
          num("Find the value of sin 30°.", 0.5, "sin 30° = 0.5 exactly."),
          num("In triangle ABC, angle B = 90°, AB = 12 cm and BC = 5 cm. Find AC in cm.", 13, "√(144 + 25) = √169 = 13 cm"),
          mcq("An angle measured upwards from the horizontal is called the angle of…", ["elevation", "depression", "reflection", "incidence"], "Elevation looks up; depression looks down."),
          num("A kite string 40 m long makes an angle of 60° with the ground. Find the height of the kite in m, to 1 decimal place.", 34.6, "h = 40 × sin 60° = 40 × 0.866 = 34.6 m", 1, 0.1),
          st("A boat is 120 m from the foot of a vertical cliff. The angle of depression of the boat from the top of the cliff is 25°. Calculate the height of the cliff.",
            "The angle of elevation from the boat is 25° (alternate angles)  [1]\ntan 25° = h ÷ 120  [1]\nh = 120 × 0.4663 = 56.0 m (3 s.f.)  [1]", 3),
        ],
      },
      {
        id: "zm_stats", title: "Statistics", estMinutes: 45, term: 3, summary: "Mean, median, mode, range, frequency tables and pie charts.",
        notes: [
          "## Types of data",
          "- **Discrete** data can only take particular values (for example, the number of siblings).",
          "- **Continuous** data can take any value in a range (for example, height, mass or time).",
          "## Averages",
          "| Measure | How to find it | Best used when |",
          "|---|---|---|",
          "| Mean | sum of the values ÷ number of values | there are no extreme values |",
          "| Median | the middle value once the data is in order | there are extreme values (outliers) |",
          "| Mode | the value that occurs most often | you want the most common value |",
          "For n ordered values, the median is the value in position (n + 1) ÷ 2.",
          "## Spread",
          "[[range = highest value − lowest value]]",
          "## Mean from a frequency table",
          "[[mean = Σfx ÷ Σf]]",
          "Multiply each value x by its frequency f, add up the products, then divide by the total frequency.",
          "## Displaying data",
          "Bar charts, pie charts, histograms and frequency polygons. In a **pie chart**, the angle for each group is (frequency ÷ total) × 360°.",
        ].join("\n"),
        examples: [
          ex("Find the mean, median, mode and range of: 4, 7, 2, 9, 4, 10, 6.", "In order: 2, 4, 4, 6, 7, 9, 10 (n = 7)\nMean = 42 ÷ 7 = 6\nMedian = 4th value = 6\nMode = 4\nRange = 10 − 2 = 8"),
          ex("Goals scored in 20 matches:\nGoals (x): 0, 1, 2, 3\nFrequency (f): 4, 8, 5, 3\nFind the mean number of goals.", "Σf = 4 + 8 + 5 + 3 = 20\nΣfx = 0 + 8 + 10 + 9 = 27\nMean = 27 ÷ 20 = 1.35 goals"),
        ],
        questions: [
          num("Find the mean of 3, 5, 7, 9, 11.", 7, "35 ÷ 5 = 7"),
          num("Find the median of 12, 3, 8, 5, 10.", 8, "In order: 3, 5, 8, 10, 12. The middle value is 8."),
          num("Find the range of 15, 22, 9, 30, 18.", 21, "30 − 9 = 21"),
          num("Find the mode of 2, 3, 3, 5, 7, 3, 5.", 3, "3 appears three times, more than any other value."),
          mcq("Which average is most affected by an extreme value?", ["Mean", "Median", "Mode", "They are all affected equally"], "The mean uses every value, so one extreme value pulls it up or down."),
          num("In a pie chart for 60 learners, 15 walk to school. What angle, in degrees, represents the walkers?", 90, "15 ÷ 60 × 360° = 90°"),
          st("The marks of 10 learners were: 45, 52, 60, 38, 71, 60, 55, 49, 60, 50.\n(a) Find the mode.\n(b) Find the median.\n(c) Find the mean.",
            "(a) Mode = 60  [1]\n(b) In order: 38, 45, 49, 50, 52, 55, 60, 60, 60, 71, so median = (52 + 55) ÷ 2 = 53.5  [2]\n(c) Sum = 540, mean = 540 ÷ 10 = 54  [2]", 5),
        ],
      },
      {
        id: "zm_prob", title: "Probability", estMinutes: 40, term: 3, summary: "The probability scale, combined events and tree diagrams.",
        notes: [
          "## The probability scale",
          "Probability measures how likely an event is, from **0 (impossible)** to **1 (certain)**. It can be written as a fraction, a decimal or a percentage.",
          "[[P(event) = number of favourable outcomes ÷ total number of possible outcomes]]",
          "This works when all outcomes are equally likely.",
          "## Complementary events",
          "[[P(not A) = 1 − P(A)]]",
          "## Combined events",
          "- **Mutually exclusive** events cannot happen together: P(A or B) = P(A) + P(B)",
          "- **Independent** events do not affect each other: P(A and B) = P(A) × P(B)",
          "## Tree diagrams",
          "- A **possibility space** lists every outcome; a table for two dice has 36 outcomes.",
          "- On a **tree diagram**, multiply **along** the branches and add **between** the end results.",
          "- **Without replacement**, the probabilities on the second set of branches change.",
          "## Relative frequency",
          "[[relative frequency = number of times the event happened ÷ number of trials]]",
          "The more trials you do, the closer the relative frequency gets to the true probability.",
        ].join("\n"),
        examples: [
          ex("A bag contains 5 red, 3 blue and 2 green beads. One bead is picked at random. Find P(blue) and P(not blue).", "Total beads = 5 + 3 + 2 = 10\nP(blue) = 3/10\nP(not blue) = 1 − 3/10 = 7/10"),
          ex("A fair coin is tossed and a fair die is rolled. Find the probability of a head and a six.", "The events are independent.\nP(head) = 1/2 and P(six) = 1/6\nP(head and six) = 1/2 × 1/6 = 1/12"),
        ],
        questions: [
          mcq("A fair die is rolled. What is P(an even number)?", ["1/2", "1/3", "1/6", "2/3"], "There are 3 even numbers (2, 4, 6) out of 6 outcomes."),
          num("The probability that it rains tomorrow is 0.3. What is the probability that it does not rain?", 0.7, "1 − 0.3 = 0.7"),
          mcq("Which of these cannot be a probability?", ["1.2", "0", "0.75", "1"], "Probabilities are always between 0 and 1."),
          mcq("Two fair coins are tossed. What is P(two heads)?", ["1/4", "1/2", "1/3", "3/4"], "1/2 × 1/2 = 1/4"),
          num("A bag has 4 red and 6 white balls. One is taken at random. Find P(red) as a decimal.", 0.4, "4 ÷ 10 = 0.4"),
          st("A box contains 3 black and 2 white pens. Two pens are taken at random without replacement.\n(a) Find the probability that both pens are black.\n(b) Find the probability that the pens are different colours.",
            "(a) 3/5 × 2/4  [1] = 6/20 = 3/10  [1]\n(b) P(BW) + P(WB) = 3/5 × 2/4 + 2/5 × 3/4  [1] = 12/20 = 3/5  [1]", 4),
        ],
      },
    ],
  };

  var CAMBRIDGE_BIOLOGY = {
    id: "syl_cie_biology_0610", board: "Cambridge", level: "IGCSE", subject: "Biology", code: "0610",
    description: "Core IGCSE Biology: organisms, cells, transport, enzymes and nutrition.",
    gradeScale: [{ grade: "A*", min: 85 }, { grade: "A", min: 75 }, { grade: "B", min: 65 }, { grade: "C", min: 55 }, { grade: "D", min: 45 }, { grade: "E", min: 35 }, { grade: "F", min: 25 }, { grade: "G", min: 15 }, { grade: "U", min: 0 }],
    topics: [
      {
        id: "cb_living", title: "Characteristics and Classification of Living Organisms", estMinutes: 35, term: 1, summary: "MRS GREN, classification groups, binomial names and keys.",
        notes: [
          "## Characteristics of living organisms",
          "All living things carry out seven life processes. Remember them as **MRS GREN**:",
          "| Letter | Process | Meaning |",
          "|---|---|---|",
          "| M | Movement | an action that causes a change of position or place |",
          "| R | Respiration | chemical reactions in cells that break down nutrients to release energy |",
          "| S | Sensitivity | detecting and responding to changes in the environment |",
          "| G | Growth | a permanent increase in size and dry mass |",
          "| R | Reproduction | processes that make more of the same kind of organism |",
          "| E | Excretion | removing waste products of metabolism and substances in excess |",
          "| N | Nutrition | taking in materials for energy, growth and development |",
          "## Classification",
          "Organisms are sorted into groups by their **shared features**. From the largest group to the smallest:",
          "[[kingdom → phylum → class → order → family → genus → species]]",
          "> Memory aid: **K**ing **P**hilip **C**ame **O**ver **F**or **G**ood **S**oup",
          "## The binomial system",
          "Every species has a two-part scientific name: the **genus** (capital letter) followed by the **species** (lower case), written in italics or underlined. Example: *Homo sapiens*.",
          "A **species** is a group of organisms that can reproduce to produce fertile offspring.",
          "## Dichotomous keys",
          "A key uses a series of paired statements, two choices at each step, to identify an organism.",
        ].join("\n"),
        examples: [
          ex("Is a car alive? It moves, uses fuel and gives out waste gases.", "No. A car shows movement and something like excretion, but it does not grow, reproduce, sense and respond on its own, or respire in cells. A living organism must show ALL seven characteristics."),
          ex("The lion's scientific name is Panthera leo. How should it be written, and what is its genus?", "Written as *Panthera leo* (italics), or underlined when handwritten.\nGenus: Panthera (capital P). Species: leo (lower case)."),
        ],
        questions: [
          mcq("Which life process releases energy from nutrients?", ["Respiration", "Excretion", "Nutrition", "Growth"], "Respiration breaks down nutrients such as glucose to release energy."),
          mcq("Which is the correct way to write the scientific name of humans?", ["*Homo sapiens*", "*homo Sapiens*", "*Homo Sapiens*", "*Sapiens homo*"], "The genus has a capital letter, the species is lower case, and the name is in italics."),
          short("What is the smallest group in the classification system?", ["species", "a species"], "Species is the smallest group; kingdom is the largest."),
          tf("Excretion is the removal of undigested food from the body.", false, "That is egestion. Excretion removes the waste products of metabolism, such as CO₂ and urea."),
          mcq("Which pair of characteristics do both plants and animals show?", ["Growth and reproduction", "Movement of the whole organism", "Photosynthesis", "Digestion of food in a gut"], "All living organisms grow and reproduce."),
          st("State the meaning of the term species. Explain why a horse and a donkey are different species even though they can breed to produce a mule.",
            "A species is a group of organisms that can reproduce to produce fertile offspring  [1]\nA mule is infertile / cannot reproduce  [1]\nSo horses and donkeys are different species  [1]", 3),
        ],
      },
      {
        id: "cb_cells", title: "Cell Structure", estMinutes: 40, term: 1, summary: "Plant, animal and bacterial cells, specialised cells, magnification.",
        notes: [
          "## Cell structures and their functions",
          "| Structure | Function | Plant | Animal |",
          "|---|---|---|---|",
          "| Cell membrane | controls what enters and leaves the cell | ✓ | ✓ |",
          "| Cytoplasm | where most chemical reactions take place | ✓ | ✓ |",
          "| Nucleus | contains the genetic material (DNA) that controls the cell | ✓ | ✓ |",
          "| Mitochondria | site of aerobic respiration | ✓ | ✓ |",
          "| Ribosomes | site of protein synthesis | ✓ | ✓ |",
          "| Cell wall | made of cellulose; gives strength and shape | ✓ | ✗ |",
          "| Chloroplasts | contain chlorophyll; site of photosynthesis | ✓ | ✗ |",
          "| Large permanent vacuole | contains cell sap; keeps the cell firm | ✓ | ✗ |",
          "Bacterial cells have **no nucleus**: their DNA is a circular chromosome, plus small rings called **plasmids**.",
          "## Specialised cells",
          "- **Red blood cell**: no nucleus and a biconcave shape, so it can carry more oxygen",
          "- **Root hair cell**: a long extension gives a large surface area to absorb water and ions",
          "- **Palisade mesophyll cell**: packed with chloroplasts for photosynthesis",
          "- **Ciliated cell**: cilia move mucus",
          "- **Sperm cell**: a tail for swimming and many mitochondria for energy",
          "## Levels of organisation",
          "[[cell → tissue → organ → organ system → organism]]",
          "## Magnification",
          "[[magnification = image size ÷ actual size]]",
          "Use the **same units** for both sizes (1 mm = 1000 µm).",
        ].join("\n"),
        examples: [
          ex("A cell measures 25 mm on a photograph. Its actual size is 0.05 mm. Calculate the magnification.", "magnification = image size ÷ actual size\n= 25 ÷ 0.05\n= ×500"),
          ex("Explain why root hair cells do not contain chloroplasts.", "Root hair cells are underground, where there is no light, so they cannot photosynthesise. Chloroplasts would be of no use to them."),
        ],
        questions: [
          mcq("Which structure is found in plant cells but not in animal cells?", ["Cell wall", "Cell membrane", "Nucleus", "Mitochondria"], "Only plant cells have a cellulose cell wall."),
          mcq("Where does aerobic respiration take place?", ["Mitochondria", "Ribosomes", "Nucleus", "Vacuole"], "Mitochondria are the site of aerobic respiration."),
          num("An image of a cell is 40 mm long and the magnification is ×400. What is the actual length in mm?", 0.1, "actual size = image size ÷ magnification = 40 ÷ 400 = 0.1 mm", 1, 0.001),
          short("What is the name of the green pigment found in chloroplasts?", ["chlorophyll"], "Chlorophyll absorbs light energy for photosynthesis."),
          tf("Red blood cells contain a large nucleus.", false, "Red blood cells have no nucleus, which leaves more room for haemoglobin."),
          mcq("Which order runs from smallest to largest?", ["cell → tissue → organ → organ system", "tissue → cell → organ → organ system", "cell → organ → tissue → organ system", "organ → tissue → cell → organ system"], "Cells form tissues, tissues form organs and organs form organ systems."),
          st("Describe two ways in which a red blood cell is adapted to carry oxygen.",
            "Any two of:\n• contains haemoglobin, which binds oxygen  [1]\n• no nucleus, so more space for haemoglobin  [1]\n• biconcave shape gives a large surface area for diffusion  [1]\n• small and flexible, so it can pass through capillaries  [1]\n(Maximum 2 marks)", 2),
        ],
      },
      {
        id: "cb_transport", title: "Movement into and out of Cells", estMinutes: 45, term: 1, summary: "Diffusion, osmosis and active transport.",
        notes: [
          "## Diffusion",
          "**Diffusion** is the net movement of particles from a region of **higher concentration** to a region of **lower concentration**, down a concentration gradient, as a result of their random movement. It does not need energy from respiration.",
          "The rate of diffusion increases with:",
          "- a larger surface area",
          "- a steeper concentration gradient",
          "- a higher temperature",
          "- a shorter distance to travel",
          "## Osmosis",
          "**Osmosis** is the net movement of **water molecules** from a region of higher water potential (a dilute solution) to a region of lower water potential (a concentrated solution), through a **partially permeable membrane**.",
          "| Solution outside the cell | Animal cell | Plant cell |",
          "|---|---|---|",
          "| More dilute than the cytoplasm | swells and may burst | becomes **turgid** (the wall stops it bursting) |",
          "| Same concentration | no change | no change |",
          "| More concentrated | shrinks | becomes **flaccid**, then **plasmolysed** |",
          "## Active transport",
          "**Active transport** moves particles **against** a concentration gradient (from low to high), using **energy from respiration** and carrier proteins in the membrane.",
          "> Example: root hair cells take in mineral ions from the soil by active transport, because the ion concentration is higher inside the root.",
        ].join("\n"),
        examples: [
          ex("A potato chip is placed in a concentrated sugar solution for an hour. Predict and explain what happens to its mass.", "Its mass decreases.\nThe sugar solution has a lower water potential than the potato cells, so water leaves the cells by osmosis through their partially permeable membranes."),
          ex("Why does diffusion happen faster on a hot day?", "At a higher temperature particles have more kinetic energy and move faster, so they spread out more quickly."),
        ],
        questions: [
          mcq("Which process needs energy from respiration?", ["Active transport", "Diffusion", "Osmosis", "All of them"], "Only active transport uses energy, because it moves particles against a concentration gradient."),
          mcq("Osmosis is the movement of which molecules?", ["Water molecules", "Glucose molecules", "All particles", "Oxygen molecules"], "Osmosis is specifically the movement of water across a partially permeable membrane."),
          tf("In diffusion, particles move from a low concentration to a high concentration.", false, "Diffusion is from high to low concentration."),
          mcq("A plant cell placed in pure water becomes…", ["Turgid", "Plasmolysed", "Flaccid", "Burst"], "Water enters by osmosis; the cell wall stops the cell bursting, so it becomes turgid."),
          short("What term describes a membrane that lets some molecules through but not others? (two words)", ["partially permeable", "selectively permeable", "semi permeable", "semi-permeable", "semipermeable"], "A partially permeable membrane lets small molecules such as water through, but not large ones such as sucrose."),
          mcq("Which change would increase the rate of diffusion into a cell?", ["A larger surface area", "A thicker membrane", "A lower temperature", "A smaller concentration gradient"], "A larger surface area lets more particles cross at once."),
          st("Explain how root hair cells absorb mineral ions from the soil, even when the concentration of ions in the soil is lower than in the cell.",
            "By active transport  [1]\nIons move against the concentration gradient  [1]\nThis uses energy from respiration / carrier proteins  [1]", 3),
        ],
      },
      {
        id: "cb_enzymes", title: "Biological Molecules and Enzymes", estMinutes: 50, term: 2, summary: "Carbohydrates, fats and proteins, food tests, and how enzymes work.",
        notes: [
          "## Biological molecules",
          "| Molecule | Made from | Elements |",
          "|---|---|---|",
          "| Carbohydrates (starch, glycogen, cellulose) | simple sugars such as glucose | C, H, O |",
          "| Fats and oils | fatty acids and glycerol | C, H, O |",
          "| Proteins | amino acids | C, H, O, N (sometimes S) |",
          "## Food tests",
          "| Test for | Reagent | Positive result |",
          "|---|---|---|",
          "| Starch | iodine solution | orange-brown → blue-black |",
          "| Reducing sugar | Benedict's solution, then heat | blue → green, yellow or brick-red |",
          "| Protein | biuret solution | blue → purple |",
          "| Fats and oils | ethanol emulsion test | a milky-white emulsion forms |",
          "| Vitamin C | DCPIP | blue → colourless |",
          "## Enzymes",
          "**Enzymes** are proteins that act as **biological catalysts**: they speed up chemical reactions without being changed themselves.",
          "- Each enzyme has an **active site** with a specific shape. Only a **complementary** substrate fits (the lock-and-key model), forming an enzyme–substrate complex.",
          "- **Temperature**: activity increases up to the **optimum** (about 37 °C for human enzymes). Above it, the active site changes shape and the enzyme is **denatured**.",
          "- **pH**: each enzyme has an optimum pH. Extreme pH also denatures enzymes.",
          "> Enzymes are not \"killed\" at high temperatures, because they were never alive. Say **denatured**.",
        ].join("\n"),
        examples: [
          ex("A student adds Benedict's solution to a fruit juice and heats it. The colour turns brick-red. What does this show?", "The juice contains a reducing sugar such as glucose. Brick-red shows a high concentration."),
          ex("Explain why an enzyme stops working at 60 °C.", "The high temperature changes the shape of the active site, so the enzyme is denatured.\nThe substrate no longer fits the active site, so no enzyme–substrate complexes form."),
        ],
        questions: [
          mcq("Which reagent is used to test for starch?", ["Iodine solution", "Benedict's solution", "Biuret solution", "Ethanol"], "Iodine turns from orange-brown to blue-black when starch is present."),
          mcq("What are proteins made from?", ["Amino acids", "Fatty acids and glycerol", "Glucose", "Starch"], "Proteins are long chains of amino acids."),
          short("What word describes an enzyme whose active site has permanently changed shape?", ["denatured"], "A denatured enzyme can no longer bind its substrate."),
          mcq("A positive biuret test shows a colour change from blue to…", ["Purple", "Brick-red", "Blue-black", "Colourless"], "Biuret turns purple when protein is present."),
          tf("Enzymes are used up in the reactions they catalyse.", false, "Catalysts are not used up; each enzyme can be used again and again."),
          num("At about what temperature, in °C, do most human enzymes work best?", 37, "Human enzymes have an optimum of about 37 °C, which is body temperature.", 1, 1),
          st("Using the lock-and-key model, explain why the enzyme amylase can break down starch but not protein.",
            "Enzymes have an active site with a specific shape  [1]\nStarch is complementary to / fits the active site of amylase  [1]\nProtein has a different shape, so it does not fit and no enzyme–substrate complex forms  [1]", 3),
        ],
      },
      {
        id: "cb_plants", title: "Plant Nutrition", estMinutes: 45, term: 2, summary: "Photosynthesis, limiting factors, leaf structure and mineral ions.",
        notes: [
          "## Photosynthesis",
          "**Photosynthesis** is the process by which plants make carbohydrates from raw materials using energy from light.",
          "[[carbon dioxide + water → glucose + oxygen  (light, chlorophyll)]]",
          "[[6CO_{2} + 6H_{2}O → C_{6}H_{12}O_{6} + 6O_{2}]]",
          "## How the plant uses glucose",
          "- in respiration, to release energy",
          "- stored as **starch**, which is insoluble so it does not affect osmosis",
          "- converted to **cellulose** for cell walls",
          "- converted to **sucrose** for transport in the phloem",
          "- combined with nitrate ions to make **amino acids** and proteins",
          "## Limiting factors",
          "The rate of photosynthesis is limited by whichever factor is in shortest supply:",
          "- light intensity",
          "- carbon dioxide concentration",
          "- temperature, because enzymes are involved",
          "## Leaf structure",
          "| Feature | Adaptation |",
          "|---|---|",
          "| Broad, thin lamina | large surface area to absorb light; short distance for gases to diffuse |",
          "| Palisade mesophyll | many chloroplasts near the upper surface |",
          "| Spongy mesophyll | air spaces let gases diffuse |",
          "| Stomata | let CO_{2} in and O_{2} out; opened and closed by guard cells |",
          "| Veins (xylem and phloem) | xylem brings water; phloem carries sucrose away |",
          "## Mineral ions",
          "- **Nitrate ions** are needed to make amino acids. Deficiency: poor growth and yellow leaves.",
          "- **Magnesium ions** are needed to make chlorophyll. Deficiency: yellowing between the veins.",
        ].join("\n"),
        examples: [
          ex("A leaf from a plant kept in the dark for 48 hours is tested with iodine. It stays orange-brown. Explain why.", "In the dark the plant cannot photosynthesise, so it makes no new glucose.\nIt has used up its stored starch in respiration, so the iodine test is negative."),
          ex("On a graph, the rate of photosynthesis rises with light intensity and then levels off. Suggest why it levels off.", "Another factor, such as carbon dioxide concentration or temperature, has become the limiting factor, so more light does not increase the rate."),
        ],
        questions: [
          mcq("Which gas do leaves take in for photosynthesis?", ["Carbon dioxide", "Oxygen", "Nitrogen", "Water vapour"], "CO₂ is a raw material for photosynthesis."),
          mcq("In which form do plants store glucose?", ["Starch", "Cellulose", "Protein", "Glycogen"], "Plants store glucose as insoluble starch. Glycogen is the animal store."),
          short("Which ion is needed to make chlorophyll?", ["magnesium", "magnesium ion", "magnesium ions", "mg", "mg2+"], "Without magnesium, leaves turn yellow between the veins."),
          tf("Photosynthesis produces oxygen as a by-product.", true, "Oxygen is released and diffuses out through the stomata."),
          mcq("Which cells open and close the stomata?", ["Guard cells", "Palisade cells", "Root hair cells", "Xylem cells"], "A pair of guard cells surrounds each stoma."),
          mcq("Why is glucose stored as starch?", ["Starch is insoluble, so it does not affect osmosis", "Starch is sweeter", "Starch dissolves easily in water", "Starch releases oxygen"], "Insoluble starch does not draw water into cells by osmosis."),
          st("Describe how you would show that light is needed for photosynthesis, using a destarched potted plant and iodine solution.",
            "Destarch the plant by keeping it in the dark for 48 hours  [1]\nCover part of a leaf with black paper or foil, then leave the plant in light for several hours  [1]\nTest the leaf for starch: boil it in water, then in ethanol to remove chlorophyll, then add iodine  [1]\nOnly the uncovered part turns blue-black, showing starch was made only where light reached  [1]", 4),
        ],
      },
      {
        id: "cb_human", title: "Human Nutrition", estMinutes: 45, term: 2, summary: "A balanced diet, the digestive system, digestive enzymes and absorption.",
        notes: [
          "## A balanced diet",
          "A **balanced diet** contains all the nutrients in the correct proportions:",
          "| Nutrient | Main use | Good sources |",
          "|---|---|---|",
          "| Carbohydrates | energy | sadza, bread, rice |",
          "| Fats | energy store, insulation | cooking oil, butter, nuts |",
          "| Proteins | growth and repair | beans, meat, fish, eggs |",
          "| Vitamin C | healthy skin and gums (lack causes scurvy) | oranges, guavas |",
          "| Vitamin D | absorbing calcium (lack causes rickets) | fish oils, sunlight on the skin |",
          "| Calcium | bones and teeth | milk, kapenta |",
          "| Iron | making haemoglobin (lack causes anaemia) | red meat, leafy greens |",
          "| Fibre | keeps food moving through the gut | vegetables, whole grains |",
          "## The digestive system",
          "[[mouth → oesophagus → stomach → small intestine → large intestine → anus]]",
          "Associated organs: salivary glands, liver (makes bile), gall bladder (stores bile) and pancreas.",
          "## Digestion",
          "- **Mechanical digestion** breaks food into smaller pieces (teeth, churning in the stomach) without changing the molecules.",
          "- **Chemical digestion** uses enzymes to break large insoluble molecules into small soluble ones.",
          "| Enzyme | Substrate → product | Made in |",
          "|---|---|---|",
          "| Amylase | starch → maltose | salivary glands, pancreas |",
          "| Protease (pepsin, trypsin) | proteins → amino acids | stomach, pancreas |",
          "| Lipase | fats → fatty acids + glycerol | pancreas |",
          "**Bile** is alkaline. It neutralises stomach acid and **emulsifies** fats into small droplets, giving lipase a larger surface area to act on.",
          "## Absorption",
          "Most absorption happens in the **ileum**. Its **villi** and microvilli give a very large surface area, with thin walls and a rich blood supply.",
        ].join("\n"),
        examples: [
          ex("Explain why bile is important even though it contains no enzymes.", "Bile emulsifies fats into small droplets, which increases the surface area for lipase to act on.\nIt is also alkaline, so it neutralises stomach acid and gives the right pH for enzymes in the small intestine."),
          ex("A child has soft, bent leg bones. Suggest which nutrient is lacking.", "Vitamin D (or calcium). This is rickets: without vitamin D, calcium is not absorbed properly, so the bones are weak."),
        ],
        questions: [
          mcq("Which enzyme breaks down starch?", ["Amylase", "Lipase", "Pepsin", "Trypsin"], "Amylase digests starch to maltose."),
          mcq("Where does most absorption of digested food take place?", ["Ileum (small intestine)", "Stomach", "Large intestine", "Oesophagus"], "The villi of the ileum give a huge surface area."),
          short("Which deficiency disease is caused by a lack of vitamin C?", ["scurvy"], "Scurvy causes bleeding gums and poor wound healing."),
          tf("Bile contains enzymes that digest fat.", false, "Bile has no enzymes. It emulsifies fat so that lipase can work faster."),
          mcq("What are the products of fat digestion?", ["Fatty acids and glycerol", "Amino acids", "Maltose", "Glucose"], "Lipase breaks fats into fatty acids and glycerol."),
          mcq("Which nutrient is mainly used for growth and repair?", ["Protein", "Carbohydrate", "Fibre", "Fat"], "Proteins provide amino acids for building new cells."),
          st("Describe three ways in which the villi of the small intestine are adapted for absorption.",
            "Any three of:\n• large surface area, with microvilli  [1]\n• thin walls, one cell thick, so a short diffusion distance  [1]\n• a good blood supply that keeps the concentration gradient steep  [1]\n• a lacteal to absorb fatty acids and glycerol  [1]\n(Maximum 3 marks)", 3),
        ],
      },
    ],
  };

  var OXFORD_PHYSICS = {
    id: "syl_oxaqa_physics_9203", board: "Oxford AQA", level: "International GCSE", subject: "Physics", code: "9203",
    description: "Forces and motion, energy, and electricity, with calculation practice.",
    gradeScale: [{ grade: "9", min: 85 }, { grade: "8", min: 75 }, { grade: "7", min: 65 }, { grade: "6", min: 57 }, { grade: "5", min: 50 }, { grade: "4", min: 42 }, { grade: "3", min: 34 }, { grade: "2", min: 25 }, { grade: "1", min: 15 }, { grade: "U", min: 0 }],
    topics: [
      {
        id: "op_forces", title: "Forces and Motion", estMinutes: 45, term: 1, summary: "Speed, acceleration, motion graphs, Newton's laws and momentum.",
        notes: [
          "## Speed, velocity and acceleration",
          "[[speed = distance ÷ time]]",
          "**Velocity** is speed in a stated direction, so it is a vector.",
          "[[acceleration = change in velocity ÷ time taken      a = (v − u) ÷ t]]",
          "Speed is measured in m/s and acceleration in m/s^2.",
          "## Graphs of motion",
          "- **Distance–time graph**: the gradient is the **speed**. A horizontal line means the object is stationary.",
          "- **Velocity–time graph**: the gradient is the **acceleration**, and the **area under the line** is the distance travelled.",
          "## Newton's laws",
          "1. An object stays at rest, or at a constant velocity, unless a **resultant force** acts on it.",
          "2. Resultant force = mass × acceleration.",
          "3. When two objects interact, they exert **equal and opposite** forces on each other.",
          "[[F = m × a]]",
          "## Weight",
          "[[weight = mass × gravitational field strength      W = mg]]",
          "On Earth, g ≈ 9.8 N/kg (often taken as 10 N/kg).",
          "## Momentum",
          "[[momentum = mass × velocity      p = mv]]",
          "In a collision, the total momentum is **conserved** when no external forces act.",
        ].join("\n"),
        examples: [
          ex("A car accelerates from 5 m/s to 25 m/s in 4 s. Find its acceleration.", "a = (v − u) ÷ t\n= (25 − 5) ÷ 4\n= 5 m/s^2"),
          ex("A resultant force of 1200 N acts on a car of mass 800 kg. Find its acceleration.", "F = ma, so a = F ÷ m\n= 1200 ÷ 800\n= 1.5 m/s^2"),
        ],
        questions: [
          num("A runner covers 400 m in 50 s. What is her average speed in m/s?", 8, "400 ÷ 50 = 8 m/s"),
          num("Find the weight, in N, of a 60 kg person where g = 10 N/kg.", 600, "W = mg = 60 × 10 = 600 N"),
          mcq("What does the gradient of a velocity–time graph represent?", ["Acceleration", "Distance", "Speed", "Momentum"], "Gradient = change in velocity ÷ time = acceleration."),
          num("Find the momentum, in kg m/s, of a 2 kg ball moving at 3 m/s.", 6, "p = mv = 2 × 3 = 6 kg m/s"),
          tf("An object moving at a constant velocity has a resultant force of zero acting on it.", true, "Newton's first law: with no resultant force, the velocity does not change."),
          st("A trolley of mass 2 kg accelerates from rest to 6 m/s in 3 s.\n(a) Calculate its acceleration.\n(b) Calculate the resultant force acting on it.",
            "(a) a = (6 − 0) ÷ 3  [1] = 2 m/s^2  [1]\n(b) F = ma = 2 × 2  [1] = 4 N  [1]", 4),
        ],
      },
      {
        id: "op_energy", title: "Energy", estMinutes: 40, term: 2, summary: "Energy stores, conservation, work, power and efficiency.",
        notes: [
          "## Energy stores and transfers",
          "Energy is stored as kinetic, gravitational potential, elastic potential, chemical, thermal and nuclear energy. It is **transferred** by forces (mechanical work), by electric current, by heating and by radiation (light and sound).",
          "## Conservation of energy",
          "Energy cannot be created or destroyed, only transferred from one store to another. Some energy is usually transferred to the surroundings as **wasted** thermal energy.",
          "## Key equations",
          "[[kinetic energy = ½ × mass × speed^2      E_{k} = ½mv^2]]",
          "[[gravitational potential energy = mass × g × height      E_{p} = mgh]]",
          "[[work done = force × distance moved      W = Fd]]",
          "[[power = energy transferred ÷ time      P = E ÷ t]]",
          "[[efficiency = useful energy output ÷ total energy input  (× 100%)]]",
          "## Energy resources",
          "- **Renewable**: solar, wind, hydroelectric (such as Kariba), geothermal and biomass. They will not run out.",
          "- **Non-renewable**: coal (such as Hwange), oil, natural gas and nuclear fuel. They will eventually run out.",
        ].join("\n"),
        examples: [
          ex("Find the kinetic energy of a 1000 kg car moving at 20 m/s.", "E_{k} = ½mv^2 = ½ × 1000 × 20^2\n= 500 × 400\n= 200 000 J (200 kJ)"),
          ex("A motor uses 500 J of electrical energy to lift a load, giving it 350 J of potential energy. Find its efficiency.", "efficiency = useful output ÷ total input\n= 350 ÷ 500\n= 0.7, which is 70%"),
        ],
        questions: [
          num("Find the gravitational potential energy, in J, gained by a 2 kg book lifted 1.5 m. (g = 10 N/kg)", 30, "E_{p} = mgh = 2 × 10 × 1.5 = 30 J"),
          num("A 60 W bulb is on for 10 s. How much energy, in J, does it transfer?", 600, "E = Pt = 60 × 10 = 600 J"),
          mcq("Which of these is a renewable energy resource?", ["Hydroelectric", "Coal", "Natural gas", "Oil"], "Hydroelectric power uses flowing water, which is continually replaced."),
          num("Find the work done, in J, when a force of 50 N moves an object 4 m.", 200, "W = Fd = 50 × 4 = 200 J"),
          tf("A machine can have an efficiency greater than 100%.", false, "That would mean creating energy, which breaks the law of conservation of energy."),
          st("A 0.5 kg ball is dropped from a height of 20 m. Ignore air resistance and take g = 10 N/kg.\n(a) Calculate the potential energy it loses.\n(b) Calculate its speed just before it hits the ground.",
            "(a) E_{p} = mgh = 0.5 × 10 × 20  [1] = 100 J  [1]\n(b) ½mv^2 = 100, so v^2 = 400  [1] and v = 20 m/s  [1]", 4),
        ],
      },
      {
        id: "op_electricity", title: "Electricity", estMinutes: 45, term: 3, summary: "Current, potential difference, resistance, circuits, power and safety.",
        notes: [
          "## Current, potential difference and resistance",
          "- **Current (I)** is the rate of flow of charge. It is measured in amperes (A) with an **ammeter** connected in **series**.",
          "- **Potential difference (V)** is measured in volts (V) with a **voltmeter** connected in **parallel**.",
          "[[V = I × R      (potential difference = current × resistance)]]",
          "[[Q = I × t      (charge = current × time)]]",
          "## Series and parallel circuits",
          "| | Series | Parallel |",
          "|---|---|---|",
          "| Current | the same everywhere | splits between the branches |",
          "| Potential difference | shared between the components | the same across each branch |",
          "| Total resistance | R = R_{1} + R_{2} | less than the smallest single resistor |",
          "## Electrical power and energy",
          "[[P = V × I      P = I^2R      E = P × t]]",
          "Energy bills use the **kilowatt-hour** (kWh): 1 kWh is the energy used by a 1 kW appliance in 1 hour.",
          "## Mains safety",
          "- **Fuse**: melts if the current is too large, breaking the circuit.",
          "- **Earth wire**: connects a metal case to earth, so a fault current flows to earth and blows the fuse.",
          "- **Circuit breaker**: a switch that trips automatically and can be reset.",
        ].join("\n"),
        examples: [
          ex("A current of 2 A flows through a 6 Ω resistor. Find the potential difference across it.", "V = IR\n= 2 × 6\n= 12 V"),
          ex("Resistors of 4 Ω and 8 Ω are connected in series to a 6 V battery. Find the current.", "Total resistance = 4 + 8 = 12 Ω\nI = V ÷ R = 6 ÷ 12 = 0.5 A"),
        ],
        questions: [
          num("Find the resistance, in Ω, of a lamp with 12 V across it and 3 A through it.", 4, "R = V ÷ I = 12 ÷ 3 = 4 Ω"),
          mcq("How is a voltmeter connected in a circuit?", ["In parallel with the component", "In series with the component", "Either way", "In place of the component"], "A voltmeter measures the difference between two points, so it goes across (in parallel with) the component."),
          num("Find the total resistance, in Ω, of 3 Ω and 5 Ω resistors in series.", 8, "In series, add the resistances: 3 + 5 = 8 Ω"),
          num("A 2 kW kettle runs for 0.5 hours. How much energy does it use, in kWh?", 1, "E = P × t = 2 kW × 0.5 h = 1 kWh"),
          mcq("What is the purpose of a fuse?", ["To break the circuit if the current is too large", "To increase the current", "To store charge", "To earth the appliance"], "The fuse wire melts when the current exceeds its rating."),
          st("A 230 V heater draws a current of 8 A.\n(a) Calculate its power.\n(b) Which fuse should be fitted: 3 A, 5 A or 13 A? Explain your choice.",
            "(a) P = VI = 230 × 8  [1] = 1840 W  [1]\n(b) 13 A  [1], the smallest rating above the normal current of 8 A (3 A and 5 A would blow in normal use)  [1]", 4),
        ],
      },
    ],
  };

  A.SeedSyllabi = [ZIMSEC_MATHS, CAMBRIDGE_BIOLOGY, OXFORD_PHYSICS];

  /** Give questions ids, shuffle MCQ options deterministically, build mock papers. */
  A.prepareSyllabus = function (syl, seed, shuffleOptions) {
    var rand = A.rng(seed || 7);
    (syl.topics || []).forEach(function (t) {
      t.id = t.id || A.uid("top");
      t.examples = t.examples || [];
      t.questions = (t.questions || []).map(function (q, i) {
        q = Object.assign({}, q);
        q.id = q.id || t.id + "_q" + (i + 1);
        if (q.type === "mcq" && shuffleOptions && Array.isArray(q.options)) {
          var correct = q.options[q.answer || 0];
          q.options = A.shuffle(q.options, rand);
          q.answer = q.options.indexOf(correct);
        }
        return q;
      });
    });
    return syl;
  };

  A.defaultPapers = function (syl) {
    var auto = [], structured = [], mixed = [];
    syl.topics.forEach(function (t) {
      var a = t.questions.filter(function (q) { return q.type !== "structured"; });
      var s = t.questions.filter(function (q) { return q.type === "structured"; });
      auto = auto.concat(a.slice(0, 3).map(function (q) { return q.id; }));
      structured = structured.concat(s.map(function (q) { return q.id; }));
      mixed = mixed.concat(a.slice(3, 5).map(function (q) { return q.id; })).concat(s.slice(0, 1).map(function (q) { return q.id; }));
    });
    return [
      { id: syl.id + "_p1", title: "Paper 1 Mock: short answers", durationMin: 30, instructions: "Answer all questions. Calculators may be used unless stated otherwise.", questionIds: auto },
      { id: syl.id + "_p2", title: "Paper 2 Mock: structured questions", durationMin: 45, instructions: "Answer all questions. Show your working. After submitting you will mark your answers against the marking scheme.", questionIds: structured },
      { id: syl.id + "_p3", title: "Full mock examination", durationMin: 60, instructions: "A mixed paper across the whole syllabus. Answer all questions.", questionIds: mixed },
    ];
  };
})(window.App);
